- name: Installing docker
  apt: pkg=docker.io state=present

- name: Install python module docker-compose (includes docker)
  pip:
    name: docker-compose
    state: present

- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: true
    